from __future__ import annotations

from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
import nbformat as nbf
import pandas as pd
import seaborn as sns


PROJECT_ROOT = Path(__file__).resolve().parents[1]
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
NOTEBOOK_PATH = PROJECT_ROOT / "notebooks" / "ecommerce_eda.ipynb"
FIGURES_DIR = PROJECT_ROOT / "reports" / "figures"

matplotlib.use("Agg")


def save_figures(orders: pd.DataFrame, segments: pd.DataFrame) -> None:
    sns.set_theme(style="whitegrid")
    completed = orders.loc[orders["status"].eq("Completed")].copy()

    monthly = (
        completed.groupby("order_month", as_index=False)
        .agg(revenue=("revenue", "sum"), profit=("profit", "sum"), orders=("order_id", "nunique"))
        .sort_values("order_month")
    )

    plt.figure(figsize=(10, 5))
    sns.lineplot(data=monthly, x="order_month", y="revenue", marker="o")
    plt.xticks(rotation=45, ha="right")
    plt.title("Monthly Revenue Trend")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "monthly_revenue_trend.png", dpi=150)
    plt.close()

    category = (
        completed.groupby("category", as_index=False)
        .agg(revenue=("revenue", "sum"), profit=("profit", "sum"))
        .sort_values("revenue", ascending=False)
    )
    plt.figure(figsize=(9, 5))
    sns.barplot(data=category, x="category", y="revenue", hue="category", palette="crest", legend=False)
    plt.title("Revenue by Category")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "revenue_by_category.png", dpi=150)
    plt.close()

    region = (
        completed.groupby("region", as_index=False)
        .agg(revenue=("revenue", "sum"), profit=("profit", "sum"))
        .sort_values("revenue", ascending=False)
    )
    plt.figure(figsize=(9, 5))
    sns.barplot(data=region, x="region", y="profit", hue="region", palette="flare", legend=False)
    plt.title("Profit by Region")
    plt.xticks(rotation=15, ha="right")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "profit_by_region.png", dpi=150)
    plt.close()

    top_products = (
        completed.groupby("product_name", as_index=False)
        .agg(revenue=("revenue", "sum"), profit=("profit", "sum"))
        .sort_values("revenue", ascending=False)
        .head(10)
    )
    plt.figure(figsize=(10, 6))
    sns.barplot(data=top_products, x="revenue", y="product_name", hue="product_name", palette="mako", legend=False)
    plt.title("Top 10 Products by Revenue")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_products_revenue.png", dpi=150)
    plt.close()

    product_perf = (
        completed.groupby(["product_name", "category"], as_index=False)
        .agg(revenue=("revenue", "sum"), profit=("profit", "sum"))
    )
    plt.figure(figsize=(9, 6))
    sns.scatterplot(data=product_perf, x="revenue", y="profit", hue="category", s=80)
    plt.title("Revenue vs Profit by Product")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "revenue_vs_profit.png", dpi=150)
    plt.close()

    plt.figure(figsize=(9, 5))
    segment_summary = (
        segments.groupby("segment", as_index=False)
        .agg(customers=("customer_id", "count"), segment_revenue=("total_revenue", "sum"))
        .sort_values("segment_revenue", ascending=False)
    )
    sns.barplot(data=segment_summary, x="segment", y="segment_revenue", hue="segment", palette="viridis", legend=False)
    plt.title("Revenue by Customer Segment")
    plt.xticks(rotation=20, ha="right")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "revenue_by_segment.png", dpi=150)
    plt.close()


def build_notebook() -> None:
    nb = nbf.v4.new_notebook()
    nb["cells"] = [
        nbf.v4.new_markdown_cell(
            "# E-Commerce Sales & Customer Analytics EDA\n"
            "This notebook explores the cleaned dataset generated by `python/data_cleaning.py` "
            "and the RFM segmentation generated by `python/customer_segmentation.py`."
        ),
        nbf.v4.new_code_cell(
            "from pathlib import Path\n"
            "import pandas as pd\n"
            "import seaborn as sns\n"
            "import matplotlib.pyplot as plt\n"
            "sns.set_theme(style='whitegrid')\n"
            "ROOT = Path.cwd().resolve().parents[0] if Path.cwd().name == 'notebooks' else Path.cwd()\n"
            "DATA = ROOT / 'data' / 'processed'\n"
            "orders = pd.read_csv(DATA / 'orders_clean.csv', parse_dates=['order_date'])\n"
            "segments = pd.read_csv(DATA / 'customer_segments.csv', parse_dates=['last_purchase_date'])\n"
            "completed = orders.query(\"status == 'Completed'\").copy()\n"
            "completed.head()"
        ),
        nbf.v4.new_markdown_cell("## Dataset Overview"),
        nbf.v4.new_code_cell(
            "overview = pd.Series({\n"
            "    'line_items': len(orders),\n"
            "    'unique_orders': completed['order_id'].nunique(),\n"
            "    'unique_customers': completed['customer_id'].nunique(),\n"
            "    'unique_products': completed['product_id'].nunique(),\n"
            "    'date_start': completed['order_date'].min(),\n"
            "    'date_end': completed['order_date'].max(),\n"
            "    'missing_values': int(orders.isna().sum().sum()),\n"
            "    'duplicate_rows': int(orders.duplicated().sum()),\n"
            "})\n"
            "overview"
        ),
        nbf.v4.new_markdown_cell("## KPI Snapshot"),
        nbf.v4.new_code_cell(
            "kpis = pd.Series({\n"
            "    'Total Revenue': round(completed['revenue'].sum(), 2),\n"
            "    'Total Profit': round(completed['profit'].sum(), 2),\n"
            "    'Total Orders': int(completed['order_id'].nunique()),\n"
            "    'Total Units Sold': int(completed['quantity'].sum()),\n"
            "    'Average Order Value': round(completed['revenue'].sum() / completed['order_id'].nunique(), 2),\n"
            "    'Average Profit per Order': round(completed['profit'].sum() / completed['order_id'].nunique(), 2),\n"
            "})\n"
            "kpis"
        ),
        nbf.v4.new_markdown_cell("## Monthly Trends"),
        nbf.v4.new_code_cell(
            "monthly = (completed.groupby('order_month', as_index=False)\n"
            "           .agg(revenue=('revenue', 'sum'), profit=('profit', 'sum'), orders=('order_id', 'nunique'))\n"
            "           .sort_values('order_month'))\n"
            "monthly['mom_revenue_growth_pct'] = monthly['revenue'].pct_change().mul(100).round(2)\n"
            "monthly"
        ),
        nbf.v4.new_code_cell(
            "plt.figure(figsize=(10, 5))\n"
            "sns.lineplot(data=monthly, x='order_month', y='revenue', marker='o')\n"
            "plt.xticks(rotation=45, ha='right')\n"
            "plt.title('Monthly Revenue Trend')\n"
            "plt.tight_layout()"
        ),
        nbf.v4.new_markdown_cell("## Product Performance"),
        nbf.v4.new_code_cell(
            "product_perf = (completed.groupby(['product_name', 'category'], as_index=False)\n"
            "                .agg(revenue=('revenue', 'sum'), profit=('profit', 'sum'), units=('quantity', 'sum')))\n"
            "top_products = product_perf.sort_values('revenue', ascending=False).head(10)\n"
            "top_products"
        ),
        nbf.v4.new_code_cell(
            "plt.figure(figsize=(10, 6))\n"
            "sns.scatterplot(data=product_perf, x='revenue', y='profit', hue='category', s=80)\n"
            "plt.title('Revenue vs Profit by Product')\n"
            "plt.tight_layout()"
        ),
        nbf.v4.new_markdown_cell("## Customer and Segment Analysis"),
        nbf.v4.new_code_cell(
            "segment_summary = (segments.groupby('segment', as_index=False)\n"
            "                   .agg(customers=('customer_id', 'count'), revenue=('total_revenue', 'sum'))\n"
            "                   .sort_values('revenue', ascending=False))\n"
            "segment_summary"
        ),
        nbf.v4.new_code_cell(
            "plt.figure(figsize=(9, 5))\n"
            "sns.barplot(data=segment_summary, x='segment', y='revenue', palette='viridis')\n"
            "plt.xticks(rotation=20, ha='right')\n"
            "plt.title('Revenue by Customer Segment')\n"
            "plt.tight_layout()"
        ),
        nbf.v4.new_markdown_cell(
            "## Geographic Analysis\n"
            "The enriched customer dimension adds city, state, and region labels so the public dataset can support "
            "regional dashboard views and frontend filtering."
        ),
        nbf.v4.new_code_cell(
            "geo = (completed.groupby(['region', 'state'], as_index=False)\n"
            "       .agg(revenue=('revenue', 'sum'), profit=('profit', 'sum'), orders=('order_id', 'nunique'))\n"
            "       .sort_values('revenue', ascending=False))\n"
            "geo.head(10)"
        ),
    ]
    nbf.write(nb, NOTEBOOK_PATH)


def main() -> None:
    orders = pd.read_csv(PROCESSED_DIR / "orders_clean.csv", parse_dates=["order_date"])
    segments = pd.read_csv(PROCESSED_DIR / "customer_segments.csv", parse_dates=["last_purchase_date"])
    save_figures(orders, segments)
    build_notebook()
    print("Generated figures in", FIGURES_DIR)
    print("Notebook created at", NOTEBOOK_PATH)


if __name__ == "__main__":
    main()
